#!/usr/bin/env bash
# Bundle E2/E5/E6 — apply the native shell configuration to the Xcode
# project generated by `npx cap add ios`. Idempotent: safe to re-run after
# a `cap sync`, and after regenerating the ios/ directory from scratch.
# Runs on macOS only (PlistBuddy).
set -euo pipefail
cd "$(dirname "$0")"

PB=/usr/libexec/PlistBuddy
PLIST=ios/App/App/Info.plist
PBX=ios/App/App.xcodeproj/project.pbxproj

if [ ! -f "$PLIST" ]; then
  echo "✗ $PLIST not found — run 'npx cap add ios' first (see setup-mac.sh)"; exit 1
fi

# --- E2: landscape only, status bar hidden, full screen -------------------
set_orientations() {
  local key="$1"
  $PB -c "Delete :$key" "$PLIST" 2>/dev/null || true
  $PB -c "Add :$key array" "$PLIST"
  $PB -c "Add :$key:0 string UIInterfaceOrientationLandscapeLeft" "$PLIST"
  $PB -c "Add :$key:1 string UIInterfaceOrientationLandscapeRight" "$PLIST"
}
set_orientations "UISupportedInterfaceOrientations"
set_orientations "UISupportedInterfaceOrientations~ipad"

set_bool() {
  $PB -c "Delete :$1" "$PLIST" 2>/dev/null || true
  $PB -c "Add :$1 bool $2" "$PLIST"
}
set_bool UIStatusBarHidden true
set_bool UIViewControllerBasedStatusBarAppearance false
set_bool UIRequiresFullScreen true
echo "✓ Info.plist: landscape-only, status bar hidden, requires full screen (E2)"

# --- TILT: pulled from the app entirely for this release (owner decision,
# July 2026) — DeviceOrientationEvent.requestPermission() silently denies
# every time inside a bare Capacitor WKWebView regardless of this plist key
# (no per-site permission store the way Safari has), so the feature needs a
# real CoreMotion-backed native plugin before it's worth shipping again. Not
# declaring NSMotionUsageDescription here on purpose: an unused permission
# is its own App Review red flag. Re-add both this and the Settings row
# together if/when that plugin lands — see app/MAC_SETUP.md.
$PB -c "Delete :NSMotionUsageDescription" "$PLIST" 2>/dev/null || true

# --- E5: export compliance — no encryption beyond HTTPS (exempt), so
# TestFlight builds skip the manual compliance question on every upload ----
set_bool ITSAppUsesNonExemptEncryption false
echo "✓ Info.plist: ITSAppUsesNonExemptEncryption = false (E5)"

# --- iOS 16 floor (owner decision, July 2026 — perf floor at A11+) --------
perl -pi -e 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' "$PBX"
[ -f ios/App/Podfile ] && perl -pi -e "s/platform :ios, '[0-9.]+'/platform :ios, '16.0'/" ios/App/Podfile
echo "✓ deployment target: iOS 16.0"

# --- E4/G: entitlements (iCloud KV + Game Center) --------------------------
cp ios-config/App.entitlements ios/App/App/App.entitlements
if ! grep -q CODE_SIGN_ENTITLEMENTS "$PBX"; then
  perl -0pi -e 's/(\n(\t+)PRODUCT_BUNDLE_IDENTIFIER = )/\n$2CODE_SIGN_ENTITLEMENTS = "App\/App.entitlements";$1/g' "$PBX"
fi
echo "✓ entitlements: Game Center + iCloud key-value storage (enable both on the App ID — MAC_SETUP.md step 4)"

# --- E5: privacy manifest ---------------------------------------------------
if [ -f ios/App/App/PrivacyInfo.xcprivacy ]; then
  cp ios-config/PrivacyInfo.xcprivacy ios/App/App/PrivacyInfo.xcprivacy
  echo "✓ PrivacyInfo.xcprivacy: no tracking, no data collected (E5)"
else
  cp ios-config/PrivacyInfo.xcprivacy ios/App/App/PrivacyInfo.xcprivacy
  echo "⚠ PrivacyInfo.xcprivacy copied, but the Capacitor template didn't include one —"
  echo "  add it to the App target in Xcode (File → Add Files…, check 'App' target)."
fi

# --- E6: single-size 1024 app icon + black launch screen -------------------
ICONSET=ios/App/App/Assets.xcassets/AppIcon.appiconset
mkdir -p "$ICONSET"
rm -f "$ICONSET"/*.png
cp resources/icon-1024.png "$ICONSET/AppIcon-1024.png"
cat > "$ICONSET/Contents.json" <<'JSON'
{
  "images" : [
    {
      "filename" : "AppIcon-1024.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON
cp ios-config/LaunchScreen.storyboard ios/App/App/Base.lproj/LaunchScreen.storyboard
echo "✓ AppIcon (single-size 1024) + black wordmark launch screen (E6)"

echo
echo "configure-ios.sh done. Remaining manual steps are in MAC_SETUP.md."
